import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#303032',
        'on-error': '#690005',
        primary: '#ecc246',
        'on-surface-variant': '#d1c5af',
        'surface-container-high': '#2a2a2c',
        'error-container': '#93000a',
        'surface-variant': '#353437',
        error: '#ffb4ab',
        'on-surface': '#e4e2e4',
        'on-secondary': '#3c2f00',
        background: '#131315',
        'on-error-container': '#ffdad6',
        'on-background': '#e4e2e4',
        'on-secondary-container': '#f1d273',
        'on-primary-container': '#4b3a00',
        'outline-variant': '#4d4635',
        'secondary-container': '#705a00',
        'surface-container': '#1f1f21',
        'on-tertiary': '#383015',
        'surface-container-lowest': '#0e0e10',
        'on-primary': '#3d2e00',
        surface: '#131315',
        'secondary-fixed-dim': '#e2c466',
        'inverse-primary': '#755b00',
        tertiary: '#d3c6a0',
        'primary-fixed-dim': '#ecc246',
        'surface-tint': '#ecc246',
        outline: '#99907b',
        'tertiary-container': '#b3a682',
        'on-tertiary-container': '#443c1f',
        secondary: '#e2c466',
        'surface-container-low': '#1b1b1d',
        'inverse-surface': '#e4e2e4',
        'surface-dim': '#131315',
        'surface-bright': '#39393b',
        'primary-container': '#c9a227',
        'surface-container-highest': '#353437',
        // Semantic risk states
        'status-safe': '#6fbf73',
        'status-hitl': '#c9a227',
        'status-risk': '#d9705f',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-4xl': '4rem',
        'space-sm': '0.5rem',
        'space-xl': '1.5rem',
        'gutter-desktop': '1.5rem',
        'space-xxs': '0.125rem',
        'gutter-mobile': '1rem',
        'space-3xl': '3rem',
        'space-2xl': '2rem',
        'space-lg': '1rem',
        'space-xs': '0.25rem',
        'space-md': '0.75rem',
        'margin-page': '2rem',
      },
      fontFamily: {
        geist: ['Geist', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
} satisfies Config
